### ISSUE TITLE
img not show

### ISSUE THREAD

**Issue by cutebear0123** [hello1234316/personalweb#3]
<img width="567" alt="截圖 2021-12-29 上午10 39 07" src="https://user-images.githubusercontent.com/72639017/147693303-20e31031-9379-4e67-971c-49b6b8cd041a.png">
<img width="337" alt="截圖 2021-12-29 上午10 39 56" src="https://user-images.githubusercontent.com/72639017/147693362-0db52a71-16dc-452d-a962-74ba5b5303ea.png">

**Comment by hello1234316** [comment]
fixed dalao 🛐

**Comment by cutebear0123** [comment]
<img width="448" alt="截圖 2021-12-29 下午7 28 55" src="https://user-images.githubusercontent.com/72639017/147719420-f542444e-b84e-45c3-b8e5-72858c3d5158.png">
SAME
U DALAO
